### ISSUE TITLE
Error in bash terminal

### ISSUE THREAD

**Issue by NikanFakhari** [BME1478H/Winter2020class#1]
Hi there, 

I have downloaded Anaconda-Navigator and GitHub on my Mac and I have created an account in Github. Currently Im just trying to confirm that I have downloaded the Anaconda python (for the assignment in my course)  in my Mac through bash terminal. This has to be confirmed by inputting the following command in the bash terminal:
"conda --version"
However when I input this into the terminal, I will receive the following error:
"zsh: command not found: conda"
I have also tried restarting my computer but Im receiving the same error again.
I would appreciate it if you can help me out to solve this issue,
Thanks
Nikan Fakhari

**Comment by RayNele** [comment]
Try a hard restart of your mac

**Comment by NikanFakhari** [comment]
I have tried that couple of times, still not working.

Nikan
________________________________

**Comment by joelostblom** [comment]
@NikanFakhari it sounds like your terminal default to the zsh shell rather than the bash shell. After you open Terminal, try running `bash` and then `conda --version` as @RayNele suggested above (I don't think you need to reboot, but I don't have a mac to test). If that works, run `conda init zsh`. After this you should be able to run `conda` from either bash or zsh.

**Comment by joelostblom** [comment]
As a bit of background, both bash and zsh are shells that run inside terminal emulators (such as Terminal.app on macOS) and they have largely interchangeable syntax. macOS switched their default shell to zsh recently, so this is likely the reason why your Terminal starts zsh instead of bash (unless you explicitly installed zsh yourself in the past).

You can start bash from zsh (and the other way around), by typing in the name of the shell you want to launch inside the current shell and then pressing enter. So If you can't get conda to work from zsh for some reason, you can instead first launch bash and then conda.

**Comment by NikanFakhari** [comment]
Hi Guys, 
Unfortunately I'm still receiving the same problem even though I have changed the shell to bash,  now when write the command:
bash-3.2$ conda --version
I will receive the following error:
bash:  conda: command not found

**Comment by georgeamatyas** [comment]
Hello Nikan,

I had the same problem. Unfortunately, all I remember doing before I stopped receiving the error was deleting any Python IDEs I had (like PyCharm) and attempting a reinstall of Anaconda.

George

**Comment by RayNele** [comment]
@NikanFakhari If it still isn't working after removal of any IDEs + reinstall, could you type in the following command and post the output so we can look into this further.

`echo  $PATH`

**Comment by NikanFakhari** [comment]
@RayNele  this is what the output looked like after I typed the commands above:
<img width="587" alt="Screen Shot 2020-01-09 at 12 51 45 PM" src="https://user-images.githubusercontent.com/59659481/72091734-da034f80-32de-11ea-9ec6-c8728f584cb8.png">

**Comment by RayNele** [comment]
So it seems anaconda has not been added to PATH. 

The first solution would be to reinstall it and hope it gets added this time, since the anaconda devs don't recommend that we add it to PATH manually

>Should I add Anaconda to the macOS or Linux PATH?

>We do not recommend adding Anaconda to the PATH manually. During installation, you will be asked “Do you wish the installer to initialize Anaconda3 by running conda init?” We recommend “yes”. If you enter “no”, then conda will not modify your shell scripts at all. In order to initialize after the installation process is done, first run source <path to conda>/bin/activate and then run conda init.

I believe those instructions are for the command line installer and not the GUI installer, but you're free to try both.

You can get both of those [here](https://www.anaconda.com/distribution/#macos) and the install instructions for both the GUI and command line install are [here](https://docs.anaconda.com/anaconda/install/mac-os/)

So try the above first with the GUI . If not, we will have to add anaconda to path manually by following the instructions [here](https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/). You also get to try out the text editor nano here. 

The path you want to add should be by default `/Users/<your-username>/anaconda3`, unless you have chosen to install it somewhere else, in which case it will be the filepath for wherever that is.

Let us know if this fixes the problem and which solution worked for you

**Comment by joelostblom** [comment]
Yeah, strange that `conda init` wasn't run automatically when you installed. You can try reinstalling like suggested above and make sure you don't opt out of automatically activating the base environment during install.

Another potentially faster way is to create a file in your home directory called `.condarc` and add the line `auto_activate_base: true`. Then try restarting the terminal and run `conda` in bash and zsh.

A third way is to find where anaconda was installed on your system and then run `source <path to conda>/bin/activate` (so probably `source /Users/<your-username>/opt/anaconda3/bin/activate` on mac). After that you should be able to run `conda init zsh`.

**Comment by NikanFakhari** [comment]
@RayNele I have tried deleting the current file for Anaconda and installed again using command lines, however the terminal still doesn't find conda and think its a strange character. However I'm am trying to add the file manually to the terminal, I was just wondering am I putting the path address the right way? I have installed anaconda3 on my desktop.
<img width="562" alt="Screen Shot 2020-01-09 at 3 12 51 PM" src="https://user-images.githubusercontent.com/59659481/72101553-f6a98280-32f2-11ea-83c4-9ada00ace150.png">

**Comment by RayNele** [comment]
@NikanFakhari foolproof way to do it is as [follows](http://osxdaily.com/2013/06/19/copy-file-folder-path-mac-os-x/):

>Select the file or folder in the OS X Finder, then hit Command+i to summon Get Info. Click and drag alongside “Where” to select the path, then hit Command+C to copy the full path to the clipboard

there are no <> brackets around your username

**Comment by NikanFakhari** [comment]
@RayNele yes I have tried all that, but still not going through even tho I have everything installed.

**Comment by RayNele** [comment]
@NikanFakhari if you could repeat the process (yeah, annoying I know, but necessary) and just mass copy paste and dump it here in a code block (or screenshot) it would be extremely helpful. 

As well as another `echo $PATH` and `ls <path to conda>` wherever it is on your desktop you installed it.

Thanks!

**Comment by joelostblom** [comment]
What's the output if you run `<path to conda>/bin/conda init zsh`? `<path to anaconda>` should be replaced with something like `/Users/nikanfakhari/anaconda3` or `/Users/nikanfakhari/opt/anaconda3`.

In you screenshot of editing paths in the nano editor, it seems like you are adding a folder on the desktop, which is not where anaconda installs by default, so unless you changed it during installation, that could be the incorrect path.

I understand it is frustrating when it is not working and at this point it might be best if someone can help you in person.

**Comment by linamnt** [comment]
Hi @NikanFakhari, sorry this has been harder to troubleshoot than expected. Given the circumstances, do you mind shooting an email to the bme1478h.ta.team@gmail.com? We can see how we can best support you either in person or otherwise?

**Comment by NikanFakhari** [comment]
Yeah I pretty much tried everything, I even had the path added, you can see it in the code below, still not finding conda, however this is my only issue, I was able to easily complete the rest of the assignment.
<img width="44" alt="Screen Shot 2020-01-10 at 1 43 38 PM" src="https://user-images.githubusercontent.com/59659481/72177781-7006ab00-33af-11ea-8b4d-77e43ff6165c.png">

**Comment by NikanFakhari** [comment]
Yeah I pretty much tried everything, I even had the path added, you can see it in the code below, still not finding conda, however this is my only issue, I was able to easily complete the rest of the assignment.
![Uploading Screen Shot 2020-01-10 at 1.43.44 PM.png…]()

**Comment by NikanFakhari** [comment]
Yeah I pretty much tried everything, I even had the path added, you can see it in the code below, still not finding conda, however this is my only issue, I was able to easily complete the rest of the assignment.
<img width="571" alt="Screen Shot 2020-01-10 at 1 43 44 PM" src="https://user-images.githubusercontent.com/59659481/72177862-a17f7680-33af-11ea-8ec4-2622d2f19957.png">

**Comment by NikanFakhari** [comment]
Yeah I pretty sure I have tried everything, I even had the path added, you can see it in the code below, still not finding conda, however this is my only issue, I was able to easily complete the rest of the assignment. can I try this on another computer and submit it with the assignment?  because if the only reason for this is to show that I have downloaded python, I have already done that and it works completely fine.
<img width="566" alt="Screen Shot 2020-01-10 at 1 55 25 PM" src="https://user-images.githubusercontent.com/59659481/72178473-eeb01800-33b0-11ea-962a-d8d0aa7e57f5.png">

**Comment by NikanFakhari** [comment]
Yeah I was able to easily do it on PC, I just downloaded anaconda on one of the PCs in the campus using my username and password, Can I just submit this as part of my assignment? 

![conda](https://user-images.githubusercontent.com/59659481/72179918-fae9a480-33b3-11ea-943e-1c2c0c6d214d.PNG)

**Comment by linamnt** [comment]
That's fine for completing the assignment.

However, going forward and to continue in the course, we should make sure this works on your computer in order to do future assignments.
