### ISSUE TITLE
A5 - Part 2d

### ISSUE THREAD

**Issue by chowd505** [BME1478H/Winter2020class#159]
![image](https://user-images.githubusercontent.com/59659816/75289134-ac6d5980-57eb-11ea-9cad-5954a11799a7.png)

"It shows as 1 commit ahead, 3 commits behind."

How should I fix this?

**Comment by joelostblom** [comment]
The commits behind are just updates I did to the issue template in the main
repo after you created your fork. For this assignment you don't need to fix
anything, and can open the PR from your fork in its current state.

If you're generally interested in how to keep your fork up to date with the
main/upstream repo, you can read detailed instructions on this github help
page
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by chowd505** [comment]
So does that mean my codes are right and I do not need to fix anything?
The assignment asks us to look for "the branch is 1 commit ahead of BME1478H:master"". 

So, is my result correct?

**Comment by joelostblom** [comment]
Yes the state of your forked repo is what we expect it to be. You're one
commit ahead (that's the changes you have made to your fork), and three
commits behind (that's the changes I made to the main repo after you
forked). All you need to do is to open a pull request if you haven't
already done so.

**Comment by chowd505** [comment]
> Yes the state of your forked repo is what we expect it to be. You're one commit ahead (that's the changes you have made to your fork), and three commits behind (that's the changes I made to the main repo after you forked). All you need to do is to open a pull request if you haven't already done so.
> […](#)

I showed the screenshot yesterday during the tutorial and they mentioned to me that as I am ahead, I need to PUSH and then PULL.
However, according to what you mentioned, I only need to PULL.
Can you please clarify as I am a bit confused here.

**Comment by joelostblom** [comment]
I can see in https://github.com/BME1478H/Winter2020class/pull/172 that you already opened a PR successfully. This is what I was referring to in my comments above, not that you should pull to your local repo. Your PR looks good, you can see if you go to the "Files changed" tab in the PR that it only adds a line to the repo, the commits that you're behind does not matter for this PR.

If you're generally interested in how to keep your fork up to date with the
main/upstream repo, you can read detailed instructions on this github help
page
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork. Following those instruction will remove the message that says you are a few commits behind, and just show that you are one commit ahead.

If this is still unclear, could you mention the TA who helped you in person using the `@` symbol, so that they can elaborate on what they meant? As I said, your PR for the assignment looks good, so for that part, nothing else is needed.

**Comment by joelostblom** [comment]
Closing this, let me know if you still have questions and we can reopen @chowd505
