### ISSUE TITLE
Supress the 'no such file or directory' message from the find command

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#17]
for f in 20180204-01 20180220-01 20180220-02 20180310-01 20180310-02 20180405-01 20180511-01; do
> cd $f
> find *.txt || echo $f is missing a notes file
> cd ..
> done
notes20180204.txt
find: *.txt: No such file or directory
20180220-01 is missing a notes file
notes.txt
notes20180310-01.txt
noteslab.txt
find: *.txt: No such file or directory
20180405-01 is missing a notes file
notes20180511-01.txt

**Comment by joelostblom** [comment]
You can try redirecting the error output to another place so that it is not printed in the terminal. This is done by appending `2>/dev/null` to your find command.

More details in the answers here:
- https://superuser.com/questions/393812/supresss-the-no-such-file-or-directory-message-from-find
- https://stackoverflow.com/questions/45575021/find-suppress-no-such-file-or-directory-errors

**Comment by rennmela** [comment]
Thank you!
