### ISSUE TITLE
Assignment 5, question 2 

### ISSUE THREAD

**Issue by fakharin** [BME1478H/Winter2020class#191]
Hi guys, 

For question two on assignment 5, I think i was able to complete the task successfully, however my pull request still appears to be zero, I was just wondering is there anything else that im supposed to do?

I am already receiving the following: 
<img width="1179" alt="Screen Shot 2020-03-01 at 2 13 36 PM" src="https://user-images.githubusercontent.com/59659481/75632150-486ddb00-5bc7-11ea-9110-7348dc849946.png">

**Comment by joelostblom** [comment]
That number reflects the PRs made to your forked repository. If you navigate to the main/upstream repository, you will see that there are multiple PRs made from students already. There should be a banner displayed where you get the options to add a PR from your fork since it is one commit ahead of main/upstream repo.

**Comment by joelostblom** [comment]
Let me know if this is still an issue and we can reopen.
