### ISSUE TITLE
A6 - Part 2 - a

### ISSUE THREAD

**Issue by sadiloai** [BME1478H/Winter2020class#193]
Hello

I am trying to search for all the rows that contain year 2014 with the following code: 

year_2014 = world_data['year'] == 2014
year_2014_subset = world_data[year_2014]

and instead of searching for year 2014 its converting all of the years to 2014 and giving me an output of 39201 rows × 14 columns

Not sure why this is happening. 

Thanks

**Comment by t-christ1** [comment]
Hi @sadiloai did you figure this out? I'm having the same issue and not sure what to change.

**Comment by RayNele** [comment]
@t-christ1  That seems to be the correct solution (which is why the issue was closed, not sure why that happened either). Could you just try to run the cells again or restart the notebook, see if anything changes. If not, please post your code here and its output. 

my best guess is that a single `=` was used instead of `==` even though that isn't reflected in the post.

**Comment by sadiloai** [comment]
I actually kept trying to run it and restarted it and I kept getting the same issue, then I found that a similar code was written in the assignment/lecture so I copied and pasted it and it started working. The codes looked completely identical so I didn't know where the problem was .

**Comment by t-christ1** [comment]
@RayNele I tried running it again and restarting the notebook but I'm still getting the same thing. This is what I have for a): 

> year_2014 = world_data['year'] == 2014
> year_2014
output: 
0        True
1        True
2        True
3        True
4        True
         ... 
39196    True
39197    True
39198    True
39199    True
39200    True
Name: year, Length: 39201, dtype: bool

and for b):

> year_2014_subset = world_data[year_2014]
> year_2014_subset
output: 
![image](https://user-images.githubusercontent.com/59661198/75837508-0f826180-5d93-11ea-85db-3919b496f29c.png)

have I looked at it too many times that im missing something??

**Comment by t-christ1** [comment]
I have also tried this for b: 
year_2014_subset = world_data[world_data['year'] == 2014]
year_2014_subset

and still get the same thing with 39201 rows

**Comment by RayNele** [comment]
@t-christ1 try loading the dataset again, since 
>39197 True
39198 True
39199 True
39200 True

should actually return false 

>39197    False
39198    False
39199    False
39200    False

so there's something wrong with your dataset.
there must be a line somewhere which converts all your years to 2014.

Try `year_2014_subset = world_data[world_data['year'] == 2014]
year_2014_subset` directly after the cell importing the dataset

**Comment by t-christ1** [comment]
just reloading the dataset worked, thanks!!
