### ISSUE TITLE
A7Q1

### ISSUE THREAD

**Issue by eowyn7** [BME1478H/Winter2020class#232]
I am working on task 1b of A7 and I got an error message saying "_cannot unpack non-iterable AxesSubplot object_". The code generates a plot but I am unsure as to what the error is saying.

![image](https://user-images.githubusercontent.com/59631118/76373682-8087c300-6317-11ea-8b5e-8784703dbad3.png)

**Comment by RayNele** [comment]
you're assigning the output of `sns.scatterplot` to both `fig` and `ax`. It doesn't like that because `sns.scatterplot` only generates one thing (figure). 

however `plt.subplots()` DOES generate two different things, the figure and the axes, therefore you can assign it to two variables.

to do a little similar test, you can try `x,y = 1` , which will give you a similar error, but with an int object, which is what `1` is.

**Comment by eowyn7** [comment]
Got it, thanks.
