### ISSUE TITLE
Confused about 'Estimator' 

### ISSUE THREAD

**Issue by t-christ1** [BME1478H/Winter2020class#234]
Hello,

I'm a bit confused about the estimator function. When should we use this vs not use it? I did not use it at all in the assignment and everything seemed to output correctly. The only confusion is for questions that require 'sum' vs 'mean' and when to use estimator for this. Could someone explain this again please?

**Comment by joelostblom** [comment]
Are you referring to when it is used in seaborn plotting functions?

If so, the screenshot below from a section from the lecture shows how it works for lineplots. Briefly, the `estimator` parameter decides what you plot when there are multiple y-values for a single x-value. In the example below, there are multiple countries for each year, so you could either plot one data point per country population, or plot an estimation/aggregation of all countries. This could e.g. be the mean of the countries or the sum, which is that change the that is made in the screenshot below (from average over time, to cumulative over time). Does that makes sense?

![image](https://user-images.githubusercontent.com/4560057/76555653-4de3e480-6455-11ea-86fe-9a5ac3ae6d52.png)

**Comment by joelostblom** [comment]
@t-christ1 Did it become clear how this works? Could I go ahead and close the issue?

**Comment by linamnt** [comment]
Just as a side note, by default, the "mean" is the estimator used when you do not specify one (i.e. in the assignment where we did not ask to change the estimator), which is why it makes no difference if you specify or not, it will use 'mean' either way.

if someone wanted to apply any other operation like 'median', 'min', 'max' or a custom function you made yourself, you would enter that in your estimator, or else 'mean' is used.

**Comment by t-christ1** [comment]
@linamnt Thank you!! That was very helpful.
