### ISSUE TITLE
Assignment 8, 1e - groupby order

### ISSUE THREAD

**Issue by John-BME** [BME1478H/Winter2020class#239]
Hi, 
When we want to groupby using "timepoints" and ROI", the order is important as there are two options:
1- summary_BOLD_time = gammas.groupby(['timepoint','ROI'])['BOLD signal'].mean()
2- summary_BOLD_time = gammas.groupby(['ROI','timepoints'])['BOLD signal'].mean()

I now the overall answer is same, but shwoing the output of first 5 rows is different, so please let us know, which order is fine.

Thanks 
John

**Comment by joelostblom** [comment]
Either way is fine for this assignment as the results are just to be displayed (and they are the same, just in different order). In general, it depends on which relationship you want to highlight. Since the narrative of the assignment task so far has already investigated the ROI groups, it makes sense to further stratify the data within these groups, i.e. dividing each ROI into timepoints.
