### ISSUE TITLE
Assignment 8, 1C 'Column not found: BOLD_signal'

### ISSUE THREAD

**Issue by DeMario96** [BME1478H/Winter2020class#243]
Im getting 'Column not found: BOLD_signal' when I try to run my code. I've tried different variations and still nothing. This is the current code I'm running and it is probably wrong but its the error code thats the bothering me:
 summary_BOLD = gammas.groupby('ROI')['BOLD_signal'].agg() 
I ran the code gammas.columns and it does show that the 'BOLD signal' is a column. Any help is welcome.

**Comment by RayNele** [comment]
There's no underscore in `'BOLD signal'` in my dataset.

**Comment by DeMario96** [comment]
But isnt the underscore supposed to indicate a space?

**Comment by RayNele** [comment]
some coding languages and operating systems/programs don't place nice with spaces in filenames, which is why I would always recommend putting underscores to denote spaces in filenames and directories.

however, underscores are NOT interchangeable with spaces in python, nor in any other language/situation.
