### ISSUE TITLE
Assignment 9: Task 3 visualizing the distribution 

### ISSUE THREAD

**Issue by vanessali12** [BME1478H/Winter2020class#248]
Between Task 3(a) and 3(b), we are asked to run a code to visualize the dataset. 
When I press run, an error message pops up, and the data visualization doesn't seem to be working. Below is a screenshot of what the error message output is. 

<img width="986" alt="Screen Shot 2020-03-22 at 6 22 46 PM" src="https://user-images.githubusercontent.com/57912362/77262142-2ddcce00-6c6a-11ea-9221-e1a64ed7fe7a.png">

**Comment by RayNele** [comment]
@vanessali12  I can't actually see the error in that screenshot, can you show the final line?

**Comment by vanessali12** [comment]
Sorry! Here is the last line of the error. 

<img width="734" alt="Screen Shot 2020-03-22 at 8 45 26 PM" src="https://user-images.githubusercontent.com/57912362/77269034-1c9dbc80-6c7e-11ea-8dae-7047bbe5c28a.png">

**Comment by RayNele** [comment]
can i see how you've subset `le_asia_1970 ` and  `le_amer_1970`?

**Comment by Azzy-BME** [comment]
I have the same error and I've subset like this:

le_asia_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['region']=='Asia')&(amer_asia_1970_2000['year']==1970),['life_expectancy']]
le_amer_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['region']=='Americas')&(amer_asia_1970_2000['year']==1970),['life_expectancy']]

**Comment by vanessali12** [comment]
^I also have the exact same subset.

**Comment by RayNele** [comment]
So whenever you put `[]` around something, it makes it a list. With `['life_expectancy']`, you've made a list of one, which interacts with python such that the dataframe you create is one dimenional ,ie: there's no second dimension. 

You can test this by running `.shape` on 
```python
le_amer_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['region']=='Americas')&(amer_asia_1970_2000['year']==1970), ['life_expectancy']]
``` 
which returns `(31,1)` 

while 
```python
le_amer_1970x = amer_asia_1970_2000.loc[(amer_asia_1970_2000['region']=='Americas')&(amer_asia_1970_2000['year']==1970), 'life_expectancy']
``` 
returns `(31,)`

notice the lack of "columns" since it's one dimensional. kdeplot can only graph things with 2 dimensions, so that's why you're getting 'single positional indexer is out of bounds'

To fix this, simply remove the square brackets around `life_expectancy`, they're redundant anyways.

**Comment by Azzy-BME** [comment]
Thanks! That was very helpful.
