### ISSUE TITLE
Assignment 3: Prediction vs Observed with/without noise

### ISSUE THREAD

**Issue by dtovbis** [BME1478H/Winter2020class#36]
For the last part of the assignment, should we use the population size with or without noise for our predicted results (when testing the varied rates?)

**Comment by joelostblom** [comment]
For the entire question 2, you should be using the `population_size_noise` variable.

**Comment by moonj94** [comment]
We have to deal with a one called 'data' and 'prediction'. We are wondering whether data refers to the population_size_noise and prediction refers to population_size

**Comment by RayNele** [comment]
`data` refers to population_size_noise


'Prediction' does in a way refer to 'population_size'; 'prediction' is generated the exact same way, but with a range of rates: `range_rate`.

The premise of the question is that we want to know the growth rate of the population, and we can't just look at the pattern because of the added noise, so we're fitting it against population data generated from different rates and comparing using mse to decide which growth rate the original `population_size_noise` data followed

**Comment by dtovbis** [comment]
Update: Looks like from the latest info on the assignment page, we are NOT adding noise to the code we use to generate prediction (using the range of rates)
