### ISSUE TITLE
A8: Help with loading gamma dataset

### ISSUE THREAD

**Issue by rchow48** [BME1478H/Winter2020class#622]
Hello! 

I seem to be having some troubles loading the seaborn fmri-gammas dataset for A8. I also noticed that it's pulling from the Fall2020 class folder? Is that the issue? I have not changed any code

![Screen Shot 2022-10-28 at 8 31 35 AM](https://user-images.githubusercontent.com/113182599/198587463-d4893b54-98e0-4cc5-ae2b-5e070dbb539a.png)

Thanks!
Ron

**Comment by JoelA1234** [comment]
Hey, I'm having the same issue. I ran sns.get_dataset_names() and it seems like it has the exercise dataset but not the gamma dataset. Unless we were intended to use the fmri dataset? 
![image](https://user-images.githubusercontent.com/94364688/198683046-5a34842e-423e-4713-b799-170e6d3a8e3f.png)

**Comment by kareemkudus** [comment]
https://github.com/mwaskom/seaborn-data/commit/0680d0056330dd34a3e363fc1c922a61aec7ed34

It looks like the gamma dataset was removed a couple of months ago.

I decided to replace

`gammas = sns.load_dataset('gammas')`

with

`gammas = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/de49440879bea4d563ccefe671fd7584cba08983/gammas.csv")`

which loads the data from a previous commit to the seaborn repository rather than from within the package itself. I hope this is okay.
