### ISSUE TITLE
A42d - Missing attribute of Experiment class

### ISSUE THREAD

**Issue by rennmeli** [BME1478H/Winter2020class#68]
![Screen Shot 2020-02-13 at 11 00 29 AM](https://user-images.githubusercontent.com/59658814/74453439-6958d100-4e50-11ea-9876-e5131b111040.png)
![Screen Shot 2020-02-13 at 11 00 36 AM](https://user-images.githubusercontent.com/59658814/74453445-6b229480-4e50-11ea-85a3-993f9c05ce14.png)
Not sure what's wrong. I posted my answer to 2a,b,c but d is erroring. Is my 2a,b,c correct?

**Comment by joelostblom** [comment]
When you type `self.mean()` inside your class, Python will try to look for an attribute/method called `mean` defined inside your class. You have not defined any attribute with that name, which is what the error message is showing. 

For the future, could you post your code as text in a markdown code block instead of as a screenshot (using tripple backticks as indicated in the [issue template](https://github.com/BME1478H/Winter2020class/blob/master/.github/ISSUE_TEMPLATE/question-template.md))? It is faster for us to troubleshoot if we can copy paste to try your code easily instead of just looking at the screenshot. Likewise, providing a detailed description of the problem and a descriptive title enables us to hep faster. I updated your title as an example.

**Comment by joelostblom** [comment]
You can use tab completion or `dir(Experiment)` to view all the defined class attributes.

**Comment by rennmeli** [comment]
# TODO: modify this basic class as per the instructions above
class Experiment:
    study = 'arthriitis'
    experimenter = 'Dr.Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
   
    def add_data(self,fnames):
        dt = np.loadtxt(fnames, delimiter = ",")
    
    def patient_summary(self,operation):
        # TODO: specify the axis, 0 or 1
        ax = 1
        # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max':
            summary_values = self.max(axis=ax)
        else:
            summary_values = self.min(axis=ax)
        return summary_values


# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number

**Comment by rennmeli** [comment]
``# TODO: modify this basic class as per the instructions above
class Experiment:
    study = 'arthriitis'
    experimenter = 'Dr.Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None

    def add_data(self,fnames):
        dt = np.loadtxt(fnames, delimiter = ",")

    def patient_summary(self,operation):
    # TODO: specify the axis, 0 or 1
        ax = 1
        # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
             summary_values = self.mean(axis=ax)
        elif operation == 'max':
              summary_values = self.max(axis=ax)
        else:
             summary_values = self.min(axis=ax)
        return summary_values
# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number``

**Comment by joelostblom** [comment]
You need three backticks,  not two. I edited your comment to fix the formatting. Let me know your results from trying what I suggested in my comments above.

**Comment by joelostblom** [comment]
Assuming this is resolved since there are no additional comments, please reopen if not.

**Comment by rennmeli** [comment]
It still isn't working.

**Comment by joelostblom** [comment]
Please reopen with a comment including the changes you have made and the new error message so that we can try to figure out what is wrong.

**Comment by rennmeli** [comment]
```
# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    mean = np.mean(patient_summary, axis=1)
    values = exp.patient_summary("mean") # get our patient means
   
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number```

**Comment by rennmeli** [comment]
![Screen Shot 2020-02-15 at 12 57 35 PM](https://user-images.githubusercontent.com/59658814/74592786-c2f90100-4ff2-11ea-8ac5-6b2fc65ec3e8.png)

**Comment by joelostblom** [comment]
`patient_summary` is a function, so you can't take the mean of it. If you want to take the mean from the returned value of a function you need to call it by appending `()`. If your function returns an array-like object than it will work, if it returns something else (such as a single value in your definition a few comments back, you might get unexptected results, so make sure it returns what you expect).

**Comment by joelostblom** [comment]
And since you are trying to take the mean over the first axis, make sure your returned array-like object has more than one dimension (`.shape`).

**Comment by rennmeli** [comment]
```# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    mean = np.mean(patient_summary.append(), axis=1)
    values = exp.patient_summary("mean") # get our patient means
   
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next sessi```

![Screen Shot 2020-02-15 at 1 11 21 PM](https://user-images.githubusercontent.com/59658814/74592977-abbb1300-4ff4-11ea-88e0-340cf2464ea5.png)

**Comment by rennmeli** [comment]
![Screen Shot 2020-02-15 at 12 57 35 PM](https://user-images.githubusercontent.com/59658814/74592982-b4134e00-4ff4-11ea-81fa-06fbbd771ac8.png)

**Comment by rennmeli** [comment]
Am I writing the mean part wrong? Not really sure what else to do.

**Comment by joelostblom** [comment]
Don't include `append`, just `mean = np.mean(patient_summary(), axis=1)`. This might work, but it depends on how you defined `patient_summary`, please post your entire code if you run into more errors.

**Comment by rennmeli** [comment]
```# TODO: modify this basic class as per the instructions above
class Experiment:
    study = 'arthriitis'
    experimenter = 'Dr.Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None

    def add_data(self,fnames):
        dt = np.loadtxt(fnames, delimiter = ",")

    def patient_summary(self,operation):
    # TODO: specify the axis, 0 or 1
        ax = 1
        # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
             summary_values = self.mean(axis=ax)
        elif operation == 'max':
              summary_values = self.max(axis=ax)
        else:
             summary_values = self.min(axis=ax)
        return summary_values

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    mean = np.mean(patient_summary(), axis=1)
    values = exp.patient_summary("mean") # get our patient means
   
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number```

**Comment by rennmeli** [comment]
![Screen Shot 2020-02-15 at 1 24 18 PM](https://user-images.githubusercontent.com/59658814/74593163-80d1be80-4ff6-11ea-8755-1486c7033f2d.png)

**Comment by joelostblom** [comment]
- Since you have defined `patient_summary` to take two arguments, you can't call it it without arguments.
- You have defined `patient_summary` as a class method, you can't call it at top level (you need to use `exp.patient_summary` in your example).
- You are already computing the mean inside the `patient_summary` method. Why do you want to take the mean of it again using `np.mean`?

Instead of your current approach, I suggest that you read the instructions to `b` again, it tells you to assign data to the already existing data attribute of the class (created in the `__init__` method) instead of the new variable `dt` that you created. If you do this you will be able to access the built-in aggregation methods (mean, etc) of the class' preexisting data attribute from within the `patient_summary` method.

**Comment by rennmeli** [comment]
Sorry not sure why you didn't say it sooner then. I'm really not sure what else to do. I've been on this question for a couple days now and the help I've been getting hasn't been very useful.

**Comment by joelostblom** [comment]
> Sorry not sure why you didn't say it sooner then

@rennmeli I responded to your latest messages where you posted the full code that you are currently running. I could not have said this sooner, since I did see the definitions of your code since you changed it and posted a new error message.

>  I'm really not sure what else to do.

Did you try the solution I suggested in my last message with `self.data` instead of `dt`?

 > I've been on this question for a couple days now and the help I've been getting hasn't been very useful.

We can't simply give you the solutions, then you would not learn anything and it would not be fair to others that come up with the solutions themselves. We are here to provide hints on how you can proceed and help with specific problems when you get stuck. This is what I have tried to do in this thread: asking for clarification, giving tips on how to troubleshoot your code, and answering specific questions. Through this process, you have resolved a few of your issues and have now encountered a new issue that I have suggested a solution for. During the couple of days that you have been stuck, you did not provide any comments on the solutions I had suggestion, so there was no indication that you were still actively working on this question.

**Comment by RayNele** [comment]
If the online help is not sufficient for you, I'd recommend showing up to the in person TA sessions for extra help. I, or one of the other TA's would be happy to help.

**Comment by joelostblom** [comment]
Further comments can also be found here https://github.com/BME1478H/Winter2020class/issues/84 in case that is helpful

**Comment by rennmeli** [comment]
You are right. The help online has not been sufficient for me, but showing up to the in person TA sessions has not been helpful either. I have tried all viable options available and I am getting nowhere. I am here to learn and don't appreciate being told I am only asking for the solution.
