### ISSUE TITLE
Assignment 4: Q2d - different results when running the code block multiple times

### ISSUE THREAD

**Issue by jamie-ly-wu** [BME1478H/Winter2020class#78]
Hello, I was able to rearrange the lines to get three file. However when I wanted to double-check and I re-ran that code block, sometimes the output is only 1 or 2 file names instead of 3.

I wonder why this could be? Thanks!

**Comment by joelostblom** [comment]
Could you post the code you are running as well as the complete output the first and second time?

**Comment by jamie-ly-wu** [comment]
![image](https://user-images.githubusercontent.com/7519902/74598244-278c7e00-503c-11ea-9a42-16deef5da21c.png)

the alternative outputs are 1 or 2 of these 3 files

**Comment by joelostblom** [comment]
Could you post all your code as text so that I can try running it myself? I would need to see you definitions of the class and its methods.

Generally, the way I would trouble shoot this would be to print values and the filename for each iteration in the loop and see if you can see a pattern that helps figuring out what is wrong.

**Comment by joelostblom** [comment]
Closing for now, please reopen if you are still experiencing the issues and include the information indicated in the previous comments.
